# Generated by Django 2.2.18 on 2021-02-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ex_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
            ],
        ),
    ]
