# Generated by Django 2.2.18 on 2021-02-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_web', '0002_ex_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingData1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field1', models.CharField(max_length=200)),
                ('Field2', models.CharField(max_length=200)),
                ('Field3', models.CharField(max_length=200)),
                ('Field4', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ex_Post',
        ),
    ]
