# Generated by Django 2.2.18 on 2021-02-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('three_web', '0003_auto_20210224_0355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SettingData1',
        ),
    ]
